package me.flamboyant.survivalrumble.powers;

public enum ChampionPowerType {
    EQUIPMENT,
    BOW,
    ENDERCHEST_STUFF,
    NO_SHIELD,

    EFFECT_STRENGH,
    EFFECT_RESISTANCE,
    EFFECT_SPEED,
    EFFECT_JUMP,
    EFFECT_FIRE_RESISTANCE,
    EFFECT_WATER_BREATHING,

    MOB_FRIEND,
    ENEMIES_DETECTION,
    NO_FALL_DAMAGE,

    SPELL_SCREAM,
    SPELL_SUMMON,
    SPELL_JUMP,
    SPELL_EXPLOSIVE_PUN,
    SPELL_JAIL,
    SPELL_ADIOS,
    SPELL_SHUFFLE,

    COME_BACK_REVIVE,
    COME_BACK_BALANCE,
    COME_BACK_JUMP_SCARE,

    DEFAULT
}
