name: SurvivalRumble
version: '${project.version}'
author: Raphael CANDELARESI (Raph' le Flamboyant)
main: me.flamboyant.survivalrumble.Main
api-version: 1.18
description: Team battle blabla
commands:
  f_sr_gametime:
    description: Get the game timer.
    permission: f_sr_gametime.use
  f_sr_questinfo:
    description: Get the game information.
    permission: f_sr_gameinfo.use
  c_sr_reset_server:
    description: Reset the server config
    permission: sr_reset_server.use
  sr_setup_start:
    description: Start the Survival Rumble plugin setup
    permission: sr_setup_start.use
  d_add_score:
    description: Cheat to add score to a team (for debug purpose only)
    permission: d_add_score.use
permissions:
  f_sr_gametime.use:
    default: true
  f_sr_questinfo.use:
    default: true
