name: SurvivalRumble
version: '${project.version}'
author: Raphael CANDELARESI (Raph' le Flamboyant)
main: me.flamboyant.survivalrumble.Main
api-version: 1.18
description: Team battle blabla
commands:
  i_gametime:
    description: Get the game timer.
    permission: i_gametime.use
  i_questinfo:
    description: Get the game quests - deprecated.
    permission: i_questinfo.use
  i_check_buff:
    description: Get the champion buff information.
    permission: i_check_buff.use
  i_class_selection:
    description: Get the classes selected by player.
    permission: i_class_selection.use
  i_headquarters:
    description: Get the tema headquarter location.
    permission: i_headquarters.use
  c_sr_reset_server:
    description: Reset the server config
    permission: sr_reset_server.use
  sr_setup_start:
    description: Start the Survival Rumble plugin setup
    permission: sr_setup_start.use
  babki:
    description: Cheat to add score to a team (for debug purpose only)
    permission: d_add_score.use
  bastoooooon:
    description: Reduces the timer to 0
    permission: bastoooooon.use
permissions:
  i_gametime.use:
    default: true
  i_questinfo.use:
    default: true
  i_check_buff.use:
    default: true
  i_class_selection.use:
    default: true
  i_headquarters.use:
    default: true
